<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #20242a; }
        .report-card { border: 1px solid #d9dee7; border-radius: 6px; padding: 12px; margin-bottom: 14px; }
        .text-muted { color: #666; }
        .small { font-size: 9px; }
        .fw-bold, strong { font-weight: bold; }
        .h4 { font-size: 18px; margin: 3px 0; }
        .h5 { font-size: 14px; margin: 0 0 8px; }
        .display-6 { font-size: 26px; }
        .text-success { color: #147a48; }
        .row { width: 100%; }
        .stat { display: inline-block; width: 23%; vertical-align: top; margin-right: 1%; }
        .chart-row { width: 100%; margin-bottom: 8px; }
        .chart-label { display: inline-block; width: 28%; vertical-align: middle; }
        .chart-track { display: inline-block; width: 58%; height: 10px; background: #f0f2f5; vertical-align: middle; }
        .chart-fill { height: 10px; background: #8f171b; }
        .chart-value { display: inline-block; width: 10%; text-align: right; font-weight: bold; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #d9dee7; padding: 6px; vertical-align: top; }
        th { background: #eef2f7; text-align: left; }
        .badge { border: 1px solid #d9dee7; border-radius: 8px; padding: 2px 5px; }
    </style>
</head>
<body>
    <div class="report-card">
        <div class="text-muted small">Africa Renewal Ministries</div>
        <div class="h4 fw-bold">{{ $quarter->name }} Quarterly Performance Report</div>
        <div class="text-muted">{{ $quarter->starts_at->format('M d, Y') }} - {{ $quarter->ends_at->format('M d, Y') }}</div>
        <div class="small text-muted">Generated by {{ $generatedBy->name }} on {{ now()->format('M d, Y h:i A') }}</div>
    </div>

    <div class="report-card">
        <span class="stat"><span class="text-muted">Goals Planned</span><br><span class="display-6">{{ $summary['goals_planned'] }}</span></span>
        <span class="stat"><span class="text-muted">Goals Achieved</span><br><span class="display-6">{{ $summary['goals_achieved'] }}</span></span>
        <span class="stat"><span class="text-muted">Average Progress</span><br><span class="display-6 text-success">{{ $summary['average_progress'] }}%</span></span>
        <span class="stat"><span class="text-muted">Pending Reviews</span><br><span class="display-6">{{ $summary['pending_reviews'] }}</span></span>
    </div>

    @include('reports.partials.quarterly-content', ['isPdf' => true])
</body>
</html>
